- name: copy the artifacts to the remote server
  copy:
    src: "/root/project/artifact.tar.gz"
    dest: ~/

- name:
  shell: |
    cd ~/
    tar -zxf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
