- name: copy the artifacts to the remote server
  copy:
    src: "~/project/artifact.tar.gz"
    dest: /home/ubuntu

- name:
  shell: |
    sudo cd /home/ubuntu
    sudo tar -zxf artifact.tar.gz
    sudo npm install
    sudo pm2 stop default
    sudo pm2 start npm -- start
